### ISSUE TITLE
US3-F3 : Consulter la liste des conférenciers

### ISSUE THREAD

**Issue by qchesnier** [cju3ry/Projet_Musee#31]
## Description : 
**En tant que** utilisateur
**Je veux** consulter la liste des conférenciers
**Afin de** pouvoir de manipuler les données liées aux conférenciers

### 🟢 Cas nominal 
**Étant donné** un utilisateur sur l'application
**Quand** je clique sur le bouton pour afficher la liste des conférenciers
**Alors** une fenêtre s'affiche avec la liste des conférenciers

### 🟠 Cas limite
**Étant donné** un utilisateur sur l'application
**Quand** Je clique sur le bouton pour afficher la liste des conférenciers et que le fichier n'a pas été importé
**Alors** La liste ne s'affiche pas, et un message d'erreur s'affiche disant que le fichier n'a pas été importé

**Comment by rlbath** [comment]
Ok

**Comment by rlbath** [comment]
Cas limite : Partie "Quand" identique au cas nominal, il faut préciser dans quelle situation cela se produit.
