### ISSUE TITLE
US4-F6 : Génération de rapports d'établissement de statistiques (pourcentage) au format pdf

### ISSUE THREAD

**Issue by qchesnier** [cju3ry/Projet_Musee#36]
## Description
**En tant que** utilisateur
**Je veux** générer des rapports d'établissement de statistiques (pourcentage) au format pdf
**Afin de** pouvoir visualiser de façon structurer les données statistiques

### 🟢Cas nominal : 
**Étant donné** un utilisateur
**Lorsque** je clique sur le bouton pour générer le rapport 
**Alors** le rapport est généré au format pdf

### 🟠Cas limite : 
**Étant donné** un utilisateur
**Lorsque** je clique sur le bouton pour générer le rapport 
**Alors** un message d'erreur s'affiche pour avertir l'utilisateur qu'il y a eu une erreur lors de la génération et l'invite à revenir en arrière

### 🔴 Cas d'erreurs : 
**Étant donné** un utilisateur
**Lorsque** je clique sur le bouton pour générer le rapport et je n'entre aucun nom pour le fichier
**Alors** un message d'erreur s'affiche et le rapport n'est pas généré 

-------------------------------------------------------------------------------------------------------------------------------------------------------

**Étant donné** un utilisateur
**Lorsque** je clique sur le bouton pour générer le rapport et j'entre un nom qui existe déjà
**Alors** un message d'erreur s'affiche et demande à l'utilisateur de saisir un nom différent

**Comment by rlbath** [comment]
Ok

**Comment by rlbath** [comment]
Cas limite et cas d'erreur : voir User Story #33.
