### ISSUE TITLE
US2-F5 : Classement des conférenciers par nombre de visites

### ISSUE THREAD

**Issue by CAZORBONNETAdrian** [cju3ry/Projet_Musee#44]
## Description
**En tant que** utilisateur
**Je peux** pouvoir afficher un classement des conférenciers par nombre de visites
**Afin de** voir quel conférencier a fait le plus de visites

### 🟢 Cas nominal : 
**Étant donné** un utilisateur
**Lorsque** je clique sur le bouton pour afficher un classement des conférenciers par nombre de visites
**Alors** un classement des conférenciers par nombre de visites s'affiche

### 🟠Cas limite : 
**Étant donné** un utilisateur
**Lorsque** je clique sur le bouton pour afficher un classement des conférenciers par nombre de visites, mais aucun classement n'est disponible
**Alors** un message s'affiche pour informer l'utilisateur que le classement n'est pas disponible et lui permet de revenir en arrière

**Comment by rlbath** [comment]
Ok

**Comment by rlbath** [comment]
Cas limite et cas d'erreur : voir User Story #45
