### ISSUE TITLE
US1-F1 : Importer les données relatives aux expositions localement

### ISSUE THREAD

**Issue by qchesnier** [cju3ry/Projet_Musee#47]
## Description
**En tant que** utilisateur
**Je veux** importer les données relatives aux expositions en local
**Afin de** pouvoir consulter les données liées aux expositions

### 🟢 Cas nominal : 
**Étant donné** Un utilisateur sur l'application
**Quand** J'importe localement les données relatives aux expositions et qu'elles sont correctement importées
**Alors** Une pop-up s'ouvre pour me dire que les données ont été importés

### 🟠Cas limite : 
**Étant donné** Un utilisateur sur l'application
**Quand** Je choisi un fichier contenant les données relatives aux expositions à importer localement et que le fichier csv est supprimer pendant l'importation
**Alors** Une pop-up s'ouvre et notifie l'utilisateur que l'importation des données n'a pas pu avoir lieux donc l'utilisateur pourra annuler l'importation

### 🔴Cas d'erreur : 
**Étant donné** Un utilisateur sur l'application
**Quand** J'essaye localement d'importer les données relatives aux expositions mais que les données sont corrompues ou incorrectes (manques de données, données non conforme)
**Alors** Un messages d'erreur s'affiche disant que le fichier contient des données corrompues ou incorrecte avec un message spécifiant l'erreur précise

---------------------------------------------------------------------------------------------------------------------------------------------------

**Étant donné** Un utilisateur sur l'application
**Quand** J'essaye localement d'importer les données relatives aux expositions mais que je me trompe de fichier
**Alors** Un messages d'erreur s'affiche disant que le fichier est mauvais

---------------------------------------------------------------------------------------------------------------------------------------------------

**Étant donné** Un utilisateur sur l'application
**Quand** J'importe localement les données relatives aux expositions et que le fichier csv ne respecte pas le format définit 
**Alors** Une pop-up s'ouvre et notifie l'utilisateur que l'importation des données n'a pas pu avoir lieux car les données sont mauvaises.

---------------------------------------------------------------------------------------------------------------------------------------------------

**Étant donné** un utilisateur sur l'application
**Quand** j'essaye localement d'importer les données relatives aux expositions mais que l'utilisateur enlève le périphérique de stockage
**Alors** un message d'erreur s'affiche disant que le fichier est introuvable

**Comment by rlbath** [comment]
Je ne comprends pas la différence entre le cas nominal et le cas d'erreur puisqu'il faut impérativement informer l'utilisateur si l'importation des données ne s'effectue pas correctement.

**Comment by rlbath** [comment]
Cas limite et cas d'erreur : voir commentaire User #50.
