### ISSUE TITLE
US3-F1 : Importer les données relative aux conférenciers localement

### ISSUE THREAD

**Issue by qchesnier** [cju3ry/Projet_Musee#49]
## Description
**En tant que** utilisateur
**Je veux** importer les données relatives aux conférenciers en local
**Afin de** pouvoir consulter les données liées aux conférenciers

### 🟢Cas nominal : 
**Étant donné** un utilisateur sur l'application
**Quand** j'importe localement les données relatives aux expositions et qu'elles sont correctement importées
**Alors** une pop-up s'ouvre pour me dire que les données ont été importés

### 🟠Cas limite : 
**Étant donné** Un utilisateur sur l'application
**Quand** Je choisi un fichier contenant les données relatives aux conférenciers à importer localement et que le fichier csv est supprimer pendant l'importation
**Alors** Une pop-up s'ouvre et notifie l'utilisateur que l'importation des données n'a pas pu avoir lieux donc l'utilisateur pourra annuler l'importation

### 🔴Cas d'erreur : 
**Étant donné** Un utilisateur sur l'application
**Quand** J'essaye localement d'importer les données relatives aux conférenciers mais que les données sont corrompues ou incorrectes (manques de données, données non conforme)
**Alors** Un messages d'erreur s'affiche disant que le fichier contient des données corrompues ou incorrecte avec un message spécifiant l'erreur précise

---------------------------------------------------------------------------------------------------------------------------------------------------

**Étant donné** un utilisateur sur l'application
**Quand** j'essaye localement d'importer les données relatives aux conférenciers mais que je me trompe de fichier
**Alors** un message d'erreur s'affiche disant que le fichier est mauvais

---------------------------------------------------------------------------------------------------------------------------------------------------

**Étant donné** un utilisateur sur l'application
**Quand** j'essaye localement d'importer les données relatives aux conférenciers mais que l'utilisateur enlève le périphérique de stockage 
**Alors** un message d'erreur s'affiche disant que le fichier est introuvable

---------------------------------------------------------------------------------------------------------------------------------------------------

**Étant donné** un utilisateur sur l'application
**Quand** j'importe localement les données relatives aux conférenciers et que le fichier csv ne respecte pas le format définit 
**Alors** une pop-up s'ouvre et notifie l'utilisateur que l'importation des données n'a pas pu avoir lieux car les données sont mauvaises.

**Comment by rlbath** [comment]
Cas limite et cas d'erreur : voir commentaire User Story #50.
