### ISSUE TITLE
US4-F1 : Importer les données relative aux visites programmés localement

### ISSUE THREAD

**Issue by qchesnier** [cju3ry/Projet_Musee#50]
## Description
**En tant que** utilisateur
**Je veux** importer les données relatives aux visites programmés en local
**Afin de** pouvoir consulter les données liées aux visites programmés

### 🟢Cas nominal : 
**Étant donné** un utilisateur sur l'application
**Quand** j'importe localement les données relatives aux expositions et qu'elles sont correctement importées
**Alors** une pop-up s'ouvre pour me dire que les données ont été importés

### 🟠Cas limite : 
**Étant donné** Un utilisateur sur l'application
**Quand** Je choisi un fichier contenant les données relatives aux visites programmées à importer localement et que le fichier csv est supprimer pendant l'importation
**Alors** Une pop-up s'ouvre et notifie l'utilisateur que l'importation des données n'a pas pu avoir lieux donc l'utilisateur pourra annuler l'importation

### 🔴Cas d'erreur : 
**Étant donné** Un utilisateur sur l'application
**Quand** J'essaye localement d'importer les données relatives aux visites programmées mais que les données sont corrompues ou incorrectes (manques de données, données non conforme)
**Alors** Un messages d'erreur s'affiche disant que le fichier contient des données corrompues ou incorrecte avec un message spécifiant l'erreur précise

----------------------------------------------------------------------------------------------------------------------------------------------------

**Étant donné** un utilisateur sur l'application
**Quand** j'essaye localement d'importer les données relatives aux visites programmées mais que je me trompe de fichier
**Alors** un message d'erreur s'affiche disant que le fichier est mauvais

----------------------------------------------------------------------------------------------------------------------------------------------------

**Étant donné** un utilisateur sur l'application
**Quand** j'essaye localement d'importer les données relatives aux visites programmées mais que l'utilisateur enlève le périphérique de stockage
**Alors** un message d'erreur s'affiche disant que le fichier est introuvable

---------------------------------------------------------------------------------------------------------------------------------------------------

**Étant donné** un utilisateur sur l'application
**Quand** j'importe localement les données relatives aux visites programmées et que le fichier csv ne respecte pas le format définit 
**Alors** une pop-up s'ouvre et notifie l'utilisateur que l'importation des données n'a pas pu avoir lieux car les données sont mauvaises.

**Comment by rlbath** [comment]
Ok

**Comment by rlbath** [comment]
Cas limite : Comment fait-on pour déterminer que le fichier est introuvable ? L'utilisateur doit choisir un fichier ou annuler l'action de choix d'un fichier. S'il choisit un fichier, on essaie de charger son contenu, sinon on annule l'importation.
Cas d'erreur : A regrouper en un seul cas, celui où le contenu du fichier est incorrect (diverses raisons sont possibles : manque de données, données non conformes, etc.) et il faut alors en informer l'utilisateur en précisant la raison de l'erreur.
